name: PyPI Deployment

on:
  push:
    branches:
      - main  # Adjust this to match your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Specify the Python version you're using

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel twine build # Install necessary packages for deployment

      - name: Build and publish
        env:
          TWINE_PASSWORD: ${{ secrets.__PYPI_API_TOKEN__ }}
        run: |
          python -m build
          twine upload dist/*
